name: movie
description: A new Flutter package project.
publish_to: none
version: 0.0.2

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: "../../infrastructure/core"
  app_core:
    path: "../../infrastructure/app_core"
  movie_storage_manager:
    path: "../../infrastructure/movie_storage_manager"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  dev_core:
    path: "../../infrastructure/dev_core"
  freezed: ^2.1.0+1
  build_runner: ^2.2.0

flutter:
