name: movie
description: A new Flutter package project.
publish_to: none
version: 0.0.1

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: "../../infrastructure/core"
  app_core:
    path: "../../infrastructure/app_core"

  modular_test: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  dev_core:
    path: "../../infrastructure/dev_core"
  freezed: ^1.1.0
  build_runner: ^2.1.11

flutter:
