name: omdb_flutter
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: "../infrastructure/core"
  search:
    path: "../features/search"
  movie:
    path: "../features/movie"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  dev_core:
    path: "../infrastructure/dev_core"

flutter:
  uses-material-design: true
