name: movie_storage_manager
description: A new Flutter package project.
publish_to: none
version: 0.0.3

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=3.10.6"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: "../core"

  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  dev_core:
    path: "../dev_core"

flutter:
