name: board
description: A new Flutter package project.
publish_to: none
version: 0.0.3

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: "../../infrastructure/core"
  app_core:
    path: "../../infrastructure/app_core"
  favorites:
    path: "../favorites"
  words:
    path: "../words"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  dev_core:
    path: "../../infrastructure/dev_core"
  freezed: ^2.4.5
  build_runner: ^2.4.6

flutter:
