name: dev_core
description: A new Flutter package project.
publish_to: none
version: 0.0.3

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=3.10.6"

dependencies:
  flutter:
    sdk: flutter

  mocktail: ^1.0.1
  fpdart: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  lints: ^3.0.0
  flutter_lints: ^3.0.0

flutter:
