#!/usr/bin/env bash

set -e

## Analyze all project
for directory in $(find . -type f -iname pubspec.yaml | awk -F pubspec.yaml '{ print $1 }'); do
  echo "checking files formart for project $directory"
  scripts/analyze-module format $directory

  echo "analyze the project $directory"
  scripts/analyze-module analyze $directory
done
