#!/usr/bin/env bash

if [ ! -d $2 ]; then
  echo "$2 isn't a valid directory"
  exit 1
fi

directory=$2
cd $directory

case "$1" in
  format)
    flutter format --set-exit-if-changed .
    ;;
  analyze)
    flutter pub get
    ;;
  *)
    echo $"Usage: $0 {format|analyze}"
    ;;
    
esac
