#!/usr/bin/env bash

set -e

## Analyze all infrastructure
for directory in $(find infrastructure -type f -iname pubspec.yaml | awk -F pubspec.yaml '{ print $1 }'); do
  echo "##########################################################"
  echo "Checking files formart for project $directory"
  echo "##########################################################"
  scripts/analyze-module format $directory

  echo "##########################################################"
  echo "Analyze the project $directory"
  echo "##########################################################"
  scripts/analyze-module analyze $directory
done

## Analyze all features
for directory in $(find features -type f -iname pubspec.yaml | awk -F pubspec.yaml '{ print $1 }'); do
  echo "##########################################################"
  echo "Checking files formart for project $directory"
  echo "##########################################################"
  scripts/analyze-module format $directory

  echo "##########################################################"
  echo "Analyze the project $directory"
  echo "##########################################################"
  scripts/analyze-module analyze $directory
done

## Analyze app
app_directory='app'
echo "##########################################################"
echo "Checking files formart for project $app_directory"
echo "##########################################################"
scripts/analyze-module format $app_directory

echo "##########################################################"
echo "Analyze the project $app_directory"
echo "##########################################################"
scripts/analyze-module analyze $app_directory
