#!/usr/bin/env bash

set -e

## Rebuild all infrastructure
for directory in $(find infrastructure -type f -iname pubspec.yaml | awk -F pubspec.yaml '{ print $1 }'); do
  echo "building $directory"
  scripts/build-module clean $directory
  scripts/build-module build $directory
  scripts/build-module generate $directory
done

## Rebuild all features
for directory in $(find features -type f -iname pubspec.yaml | awk -F pubspec.yaml '{ print $1 }'); do
  echo "building $directory"
  scripts/build-module clean $directory
  scripts/build-module build $directory
  scripts/build-module generate $directory
done

## Rebuild app
echo "building app"
app_directory='app'
scripts/build-module clean $app_directory
scripts/build-module build $app_directory
scripts/build-module generate $app_directory
