#!/usr/bin/env bash

if [ ! -d $2 ]; then
  echo "$2 isn't a valid directory"
  exit 1
fi

directory=$2
cd $directory

case "$1" in
  clean)
    echo "... Cleaning project $directory"
    flutter clean
    if [ -f pubspec.lock ]; then
      rm pubspec.lock
    fi
    ;;
  build)
    echo "... Installing dependencies to project $directory"
    flutter pub get
    ;;
  generate)
    grep -qi build_runner pubspec.yaml
    if [ $? -eq 0 ]; then
      echo "... Generating code to $directory project"
      flutter pub run build_runner build --delete-conflicting-outputs
    fi

    exit 0;
    ;;
  upgrade)
    flutter pub upgrade
    ;;
  *)
    echo $"Usages: $0 {clean|build|upgrade|generate}"
    ;;
    
esac
