#!/usr/bin/env bash

set -e

## Rebuild all project
for directory in $(find . -type f -iname pubspec.yaml | awk -F pubspec.yaml '{ print $1 }'); do
  echo "building $directory"
  scripts/build-module clean $directory
  scripts/build-module build $directory
  scripts/build-module generate $directory
done
