#!/usr/bin/env bash

set -e

## Percent all infrastructure
for directory in $(find infrastructure -type f -iname pubspec.yaml | awk -F pubspec.yaml '{ print $1 }'); do 
  path_coverage="${directory}coverage/lcov.info"
  if [ -f ${path_coverage} ]; then    

    percentage_rate=$(lcov --summary "$path_coverage" | grep "lines......" | cut -d ' ' -f 4 | cut -d '%' -f 1)
    echo "Percent $path_coverage => $percentage_rate%"
  fi  
done

## Percent all features
for directory in $(find features -type f -iname pubspec.yaml | awk -F pubspec.yaml '{ print $1 }'); do 
  path_coverage="${directory}coverage/lcov.info"
  if [ -f ${path_coverage} ]; then    

    percentage_rate=$(lcov --summary "$path_coverage" | grep "lines......" | cut -d ' ' -f 4 | cut -d '%' -f 1)
    echo "Percent $path_coverage => $percentage_rate%"
  fi  
done

app_directory='app'
path_coverage="${app_directory}/coverage/lcov.info"
if [ -f ${path_coverage} ]; then
  percentage_rate=$(lcov --summary "$path_coverage" | grep "lines......" | cut -d ' ' -f 4 | cut -d '%' -f 1)
  echo "Percent $path_coverage => $percentage_rate%"
fi

echo "General percent ----"
path_coverage="./coverage/lcov.info"
if [ -f ${path_coverage} ]; then
  percentage_rate=$(lcov --summary "$path_coverage" | grep "lines......" | cut -d ' ' -f 4 | cut -d '%' -f 1)
  echo "Percent => $percentage_rate%"
fi

code_coverage=$(lcov --list ${path_coverage} | sed -n "s/.*Total:|\([^%]*\)%.*/\1/p")
echo "Current Code Coverage: ${code_coverage}"
