#!/usr/bin/env bash

set -e

path_coverage=$1

percentage_rate=$(lcov --summary "$path_coverage" | grep "lines......" | cut -d ' ' -f 4 | cut -d '%' -f 1)

echo "Percentagem $path_coverage => $percentage_rate%"
