#!/usr/bin/env bash

set -e

if [ ! -f coverage/lcov.info ]; then
  echo "Arquivo lcov.info não encontrado. Rode o comando \`make merge-modules\`"
  exit 0
fi

## Gera html
genhtml coverage/lcov.info -o coverage -p `pwd` --legend --precision=2

## Aber arquivo
open coverage/index.html
