#!/usr/bin/env bash

if [ ! -d $2 ]; then
  echo "$2 isn't a valid directory"
  exit 1
fi

directory=$2
root_directory=$3
cd $directory

case "$1" in
  merge) 
    cat ./coverage/lcov.info > $root_directory    
    # sed "$seed_directory" ./coverage/lcov.info >> $root_directory
    echo "directory $directory"
    file='coverage/lcov.info'
    bash_directory="$directory$file"
    echo "bash $bash_directory"
    # sed "s/^SF:.*lib/SF:bash_package\/lib/g" $bash_directory >> $root_directory
    sed "s/^SF:.*lib/SF:bash_package\/lib/g" ./coverage/lcov.info >> $root_directory
    ;;
  *)
    echo $"Usae: $0 {merge}"
    ;;
esac
