#!/usr/bin/env bash

if [ ! -d $2 ]; then
  echo "$2 isn't a valid directory"
  exit 1
fi

directory=$2
cd $directory

case "$1" in
  test)
    flutter test --coverage
    ;;
  *)
    echo $"Usage: $0 {test}"
    ;;
    
esac
