#!/usr/bin/env bash

set -e

## Test all project
for directory in $(find . -type f -iname pubspec.yaml | awk -F pubspec.yaml '{ print $1 }'); do
  echo "testing project $directory"
  scripts/test-module test $directory
done
