#!/usr/bin/env bash

if [ ! -d $2 ]; then
  echo "$2 isn't a valid directory"
  exit 1
fi

directory=$2
cd $directory

if [ ! -d test ]; then
  echo " => project $directory don't have test"
  exit 0
fi

if [[ -z $(find test/ -type f -iname '*_test.dart') ]]; then
  echo " => project $directory don't have test"
  exit 0
fi

case "$1" in
  test)
    flutter test --coverage
    ;;
  *)
    echo $"Usage: $0 {test}"
    ;;
    
esac
