name: search
description: A new Flutter package project.
publish_to: none
version: 0.0.1

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: "../../infrastructure/core"
  dartz: ^0.10.1
  mocktail: ^0.3.0
  equatable: ^2.0.3
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  rxdart: ^0.27.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  bloc_test: ^9.0.3

flutter:
  uses-material-design: true
