name: Flutter CI

# This workflow is triggered on pushes to the repository.

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    name: Flutter Build
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v2
      # Setup Java environment
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      # Setup Ruby environment
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      # Setup Flutter environment
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.2'
          channel: 'stable'

      - name: Flutter Version
        run: flutter --version

      - name: Install dependencies
        run: scripts/install-ci-dependencies

      - name: Get all Flutter Packages
        run: make build-modules        

      - name: Run Flutter Analyse
        run: make analyze-modules

      - name: Run Danger
        run: scripts/run-danger

      - name: Run Flutter Test
        run: make test-modules

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload coverage to Codacy
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
